name: project_2048
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  colorful_safe_area: ^0.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2
  lint: ^1.3.0
  page_transition: ^1.1.7+6
  provider: ^4.3.3
  simple_gesture_detector: ^0.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
